language: elixir

elixir:
  - '1.9.4'
otp_release:
  - '22.0'

addons:
  postgresql: '9.4'

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create ecto.migrate event_store.create event_store.init

script:
  - mix dialyzer
  - mix test